fix: Added Gatsby Cache Clear feature

diff --git a/.github/workflows/clear-actions-cache.yml b/.github/workflows/clear-actions-cache.yml
--- a/.github/workflows/clear-actions-cache.yml
+++ b/.github/workflows/clear-actions-cache.yml
@@ -10,14 +10,31 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v4
 
+      - name: Detect package manager
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "manager=yarn" >> $GITHUB_OUTPUT
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "manager=npm" >> $GITHUB_OUTPUT
+          else
+            echo "Unable to determine package manager"
+            exit 1
+          fi
+
       - name: Delete Cache Folders
         run: |
           rm -rf node_modules
           rm -rf .cache
           rm -rf ~/.npm
           rm -rf ~/.cache/ms-playwright
-          npm run clean
           echo "Cache folders deleted."
+
+      - name: Install Dependencies
+        run: ${{ steps.detect-package-manager.outputs.manager }} install
+
+      - name: Clean Gatsby Cache
+        run: ${{ steps.detect-package-manager.outputs.manager }} run clean
 
       - name: Confirm Cache Deletion
         run: |
